# CMake generated Testfile for 
# Source directory: /home/fabu/桌面/planning_tmp/InfiniTrain/tests/optimizer
# Build directory: /home/fabu/桌面/planning_tmp/InfiniTrain/build_cpu/tests/optimizer
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("/home/fabu/桌面/planning_tmp/InfiniTrain/build_cpu/tests/optimizer/test_optimizer_cpu[1]_include.cmake")
add_test([=[test_optimizer_cuda]=] "/home/fabu/桌面/planning_tmp/InfiniTrain/build_cpu/tests/optimizer/test_optimizer_cuda" "--gtest_filter=CUDA/*")
set_tests_properties([=[test_optimizer_cuda]=] PROPERTIES  LABELS "cuda" TIMEOUT "10" _BACKTRACE_TRIPLES "/home/fabu/桌面/planning_tmp/InfiniTrain/cmake/test_macros.cmake;95;add_test;/home/fabu/桌面/planning_tmp/InfiniTrain/cmake/test_macros.cmake;149;infini_train_add_test;/home/fabu/桌面/planning_tmp/InfiniTrain/tests/optimizer/CMakeLists.txt;7;infini_train_add_test_suite;/home/fabu/桌面/planning_tmp/InfiniTrain/tests/optimizer/CMakeLists.txt;0;")
add_test([=[OptimizerParameterNamesTest.DistributedOptimizerPropagatesNamesToShardOptimizer]=] "/usr/bin/cmake" "-E" "env" "INFINI_RUN_ID=optimizer_ctest" "torchrun" "--standalone" "--no-python" "--nproc_per_node=2" "/home/fabu/桌面/planning_tmp/InfiniTrain/build_cpu/tests/optimizer/test_optimizer_cuda" "--gtest_filter=CUDA/OptimizerParameterNamesTest.DistributedOptimizerPropagatesNamesToShardOptimizer/*")
set_tests_properties([=[OptimizerParameterNamesTest.DistributedOptimizerPropagatesNamesToShardOptimizer]=] PROPERTIES  LABELS "cuda;distributed" TIMEOUT "30" _BACKTRACE_TRIPLES "/home/fabu/桌面/planning_tmp/InfiniTrain/tests/optimizer/CMakeLists.txt;11;add_test;/home/fabu/桌面/planning_tmp/InfiniTrain/tests/optimizer/CMakeLists.txt;0;")
add_test([=[OptimizerParameterNamesTest.DistributedOptimizerClipGradNormUsesGlobalShardNorm]=] "/usr/bin/cmake" "-E" "env" "INFINI_RUN_ID=optimizer_ctest" "torchrun" "--standalone" "--no-python" "--nproc_per_node=2" "/home/fabu/桌面/planning_tmp/InfiniTrain/build_cpu/tests/optimizer/test_optimizer_cuda" "--gtest_filter=CUDA/OptimizerParameterNamesTest.DistributedOptimizerClipGradNormUsesGlobalShardNorm/*")
set_tests_properties([=[OptimizerParameterNamesTest.DistributedOptimizerClipGradNormUsesGlobalShardNorm]=] PROPERTIES  LABELS "cuda;distributed" TIMEOUT "30" _BACKTRACE_TRIPLES "/home/fabu/桌面/planning_tmp/InfiniTrain/tests/optimizer/CMakeLists.txt;24;add_test;/home/fabu/桌面/planning_tmp/InfiniTrain/tests/optimizer/CMakeLists.txt;0;")
add_test([=[OptimizerParameterNamesTest.DistributedOptimizerClipGradNormUsesZero2LocalShard]=] "/usr/bin/cmake" "-E" "env" "INFINI_RUN_ID=optimizer_zero2_ctest" "torchrun" "--standalone" "--no-python" "--nproc_per_node=2" "/home/fabu/桌面/planning_tmp/InfiniTrain/build_cpu/tests/optimizer/test_optimizer_cuda" "--gtest_filter=CUDA/OptimizerParameterNamesTest.DistributedOptimizerClipGradNormUsesZero2LocalShard/*")
set_tests_properties([=[OptimizerParameterNamesTest.DistributedOptimizerClipGradNormUsesZero2LocalShard]=] PROPERTIES  LABELS "cuda;distributed" TIMEOUT "30" _BACKTRACE_TRIPLES "/home/fabu/桌面/planning_tmp/InfiniTrain/tests/optimizer/CMakeLists.txt;37;add_test;/home/fabu/桌面/planning_tmp/InfiniTrain/tests/optimizer/CMakeLists.txt;0;")
add_test([=[OptimizerParameterNamesTest.DistributedOptimizerClipGradNormHandlesEmptyLocalShard]=] "/usr/bin/cmake" "-E" "env" "INFINI_RUN_ID=optimizer_empty_ctest" "torchrun" "--standalone" "--no-python" "--nproc_per_node=2" "/home/fabu/桌面/planning_tmp/InfiniTrain/build_cpu/tests/optimizer/test_optimizer_cuda" "--gtest_filter=CUDA/OptimizerParameterNamesTest.DistributedOptimizerClipGradNormHandlesEmptyLocalShard/*")
set_tests_properties([=[OptimizerParameterNamesTest.DistributedOptimizerClipGradNormHandlesEmptyLocalShard]=] PROPERTIES  LABELS "cuda;distributed" TIMEOUT "30" _BACKTRACE_TRIPLES "/home/fabu/桌面/planning_tmp/InfiniTrain/tests/optimizer/CMakeLists.txt;50;add_test;/home/fabu/桌面/planning_tmp/InfiniTrain/tests/optimizer/CMakeLists.txt;0;")
